"""empty message

Revision ID: 74e42a6db9eb
Revises: 
Create Date: 2023-09-22 16:53:01.242961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74e42a6db9eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password', sa.LargeBinary(), nullable=True),
    sa.Column('oauth_github', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('flask_dance_oauth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('token', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('auction_items_ending')
    op.drop_table('auction_items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auction_items',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('image', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('title', mysql.TEXT(), nullable=False),
    sa.Column('url', mysql.TEXT(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('ends', mysql.DATETIME(), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('current', mysql.FLOAT(), nullable=False),
    sa.Column('open', mysql.FLOAT(), nullable=False),
    sa.Column('reserve', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('bids', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('business', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('updated', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('auction_items_ending',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('image', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('title', mysql.TEXT(), nullable=False),
    sa.Column('url', mysql.TEXT(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('ends', mysql.DATETIME(), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('current', mysql.FLOAT(), nullable=False),
    sa.Column('open', mysql.FLOAT(), nullable=False),
    sa.Column('reserve', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('bids', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('business', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('updated', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('flask_dance_oauth')
    op.drop_table('users')
    # ### end Alembic commands ###
